name: Test Release Build

on:
  workflow_dispatch:  # Manual trigger

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Trigger MacOS Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: macos-nightly.yml
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Trigger Windows Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: windows-nightly.yml
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Trigger Linux x86_64 Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: linux-x86_64-nightly.yml
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Trigger Linux ARM64 Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: linux-aarch64-nightly.yml
          token: ${{ secrets.PAT_TOKEN }} 